spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME} sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: h2