name: CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Deploy CD
    runs-on: ubuntu-latest

    steps:
      - name: 레포지토리를 가져온다
        uses: actions/checkout@v4

      - name: 자바 17을 설치한다
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle 명령 실행을 위해 권한을 부여한다
        run: chmod +x gradlew

      - name: Gradle 로 build 를 수행한다
        run: ./gradlew clean build

      - name: Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops_study:latest .

      - name: docker Hub 푸쉬
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops_study:latest

      - name: Deploy with push
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          # 이미 멈춰있어서 발생하는 예외를 방지하기 위해 || true 설정
          script: |
            sudo docker stop devops_study || true 
            sudo docker pull eunchannam/devops_study:latest
            sudo docker container prune -f 
            sudo docker run -d --log-driver=syslog --env-file .env \
            -p 8080:8080 --name devops_study \
            ${{ secrets.DOCKERHUB_USERNAME }}/devops_study:latest
            
